#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "bar"
    default_indent = 4
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = false
    autocomplete_method = "coc"
    snippet_engine = "neosnippet"

    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]

    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

#bootstrap_before = 'myspacevim#before'
#bootstrap_after = 'myspacevim#after'

    filemanager = "nerdtree"
    filetree_direction = "left"
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_delay = 200

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "checkers"

[[layers]]
  name = "VersionControl"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "core#statusline"

[[layers]]
name = "core#tabline"

[[layers]]
    name = "incsearch"

[[layers]]
  name = "core"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
name = "lsp"

[[layers]]
  name = "lang#vim"

[[layers]]
    name = "denite"

[[layers]]
  name = "tools"

[[layers]]
name = "mail"

[[layers]]
  name = "unite"

[[layers]]
name = "ui"

[[layers]]
name = "ctrlspace"

[[layers]]
  name = "edit"

[[layers]]
name = "ui"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

