vim.api.nvim_set_var("airline#extensions#tabline#enabled", 1)
vim.api.nvim_set_var("airline#extensions#tabline#left_sep", " ")
vim.api.nvim_set_var("airline#extensions#tabline#left_alt_sep", "|")
vim.api.nvim_set_var("airline#extensions#tabline#formatter", "unique_tail_improved")
vim.api.nvim_set_var("airline#extensions#tabline#buffer_nr_show", 1)
