vim.api.nvim_set_var("sonokai_style", "atlantis")
vim.api.nvim_set_var("sonokai_enable_italic", 1)
vim.api.nvim_set_var("sonokai_disable_italic_comment", 1)
vim.api.nvim_set_var("sonokai_better_performance", 1)
vim.api.nvim_command("colorscheme sonokai")
vim.api.nvim_set_var("airline_theme", "sonokai")
