local M = {}

M.icons = {
    abc = '',
    arrowReturn = '',
    bomb = '',
    box = '',
    buffer = '﬘',
    calculator = '',
    checkSquare = '',
    comment = '',
    container = '',
    cubeTree = '',
    curlies = '',
    chevronRight = '',
    caretRight = '',
    database = '﬘',
    emptyBox = '',
    error = '',
    errorOutline = '',
    errorSlash = 'ﰸ',
    f = '',
    fileBg = '',
    fileCopy = '',
    fileCutCorner = '',
    fileNoBg = '',
    fileNoLines = '',
    fileNoLinesBg = '',
    folder = '',
    folderNoBg = '',
    folderOpen = '',
    folderOpen2 = 'ﱮ',
    folderOpenNoBg = '',
    forbidden = '',
    gears = '',
    git = '',
    gitAdd = '',
    gitChange = '柳',
    gitRemove = '',
    happyFace = 'ﲃ',
    hexCutOut = '',
    info = '',
    infoOutline = '',
    key = '',
    light = '',
    lightbulb = '',
    lightbulbOutline = '',
    list = '',
    m = 'm',
    numbers = '',
    paint = '',
    paragraph = '',
    pencil = '',
    pie = '',
    rectangleIntersect = '練',
    ribbon = '',
    ribbonNoBg = '',
    ruler = '塞',
    scissors = '',
    scope = '',
    search = '',
    settings = '',
    snippet = '',
    questionCircle = '',
    sort = '',
    spell = '暈',
    t = '',
    telescope = '',
    terminal = '',
    threeDots = '',
    threeDotsBoxed = '',
    timer = '',
    toggleSelected = '蘒',
    trash = '',
    tree = '',
    treeDiagram = '',
    up_hexagon = '',
    vim = '',
    warningCircle = '',
    warningTriangle = '',
    warningTriangleNoBg = '',
    wrench = '',
    text = '',
    method = '',
    func = '',
    constructor = '',
    field = '',
    variable = '',
    class = '',
    interface = '',
    module = '',
    property = '',
    unit = '',
    value = '',
    enum = '',
    keyword = '',
    color = '',
    file = '',
    reference = '',
    enumMember = '',
    constant = '',
    struct = '',
    event = '',
    operator = '',
    typeParameter = '',
    array = '',
    number = '',
    string = '',
    boolean = '蘒',
    object = '',
    lock = '',
    circle = '',
    bigCircle = '',
    bigUnfilledCircle = '',
    close = '',
    newFile = '',
    project = '',
    dashboard = '',
    history = '',
    bug = '',
    code = '',
    gear = '',
    package = '',
    signIn = '',
    check = '',
    fire = '',
    note = '',
    bookMark = '',
    table = '',
    calendar = '',
    robot = 'ﮧ',
    squirrel = '',
    tag = '',
    watch = '',
    left = '',
    right = ''
}

local symbols = {
    File = { icon = '', hl = 'TSURI' },
    Module = { icon = '', hl = 'TSNamespace' },
    Namespace = { icon = '', hl = 'TSNamespace' },
    Package = { icon = '', hl = 'TSNamespace' },
    Class = { icon = '𝓒', hl = 'TSType' },
    Method = { icon = 'ƒ', hl = 'TSMethod' },
    Property = { icon = '', hl = 'TSMethod' },
    Field = { icon = '', hl = 'TSField' },
    Constructor = { icon = '', hl = 'TSConstructor' },
    Enum = { icon = 'ℰ', hl = 'TSType' },
    Interface = { icon = 'ﰮ', hl = 'TSType' },
    Function = { icon = '', hl = 'TSFunction' },
    Variable = { icon = '', hl = 'TSConstant' },
    Constant = { icon = '', hl = 'TSConstant' },
    String = { icon = '𝓐', hl = 'TSString' },
    Number = { icon = '#', hl = 'TSNumber' },
    Boolean = { icon = '⊨', hl = 'TSBoolean' },
    Array = { icon = '', hl = 'TSConstant' },
    Object = { icon = '⦿', hl = 'TSType' },
    Key = { icon = '🔐', hl = 'TSType' },
    Null = { icon = 'NULL', hl = 'TSType' },
    EnumMember = { icon = '', hl = 'TSField' },
    Struct = { icon = '𝓢', hl = 'TSType' },
    Event = { icon = '🗲', hl = 'TSType' },
    Operator = { icon = '+', hl = 'TSOperator' },
    TypeParameter = { icon = '𝙏', hl = 'TSParameter' }
}

M.lspkind = {
    Text = M.icons.abc,
    Method = M.icons.method,
    Function = M.icons.f,
    Constructor = M.icons.constructor,
    Field = M.icons.field,
    Variable = M.icons.variable,
    Class = M.icons.class,
    Interface = M.icons.interface,
    Module = M.icons.module,
    Property = M.icons.property,
    Unit = M.icons.unit,
    Value = M.icons.value,
    Enum = M.icons.enum,
    Keyword = M.icons.keyword,
    Snippet = M.icons.snippet,
    Color = M.icons.color,
    File = M.icons.file,
    Reference = M.icons.reference,
    Folder = M.icons.folder,
    EnumMember = M.icons.enumMember,
    Constant = M.icons.constant,
    Struct = M.icons.struct,
    Event = M.icons.event,
    Operator = M.icons.operator,
    TypeParameter = M.icons.typeParameter
}

M.lsp = {
    error = M.icons.error,
    info = M.icons.infoOutline,
    hint = M.icons.lightbulb,
    warn = M.icons.warningTriangle

}

M.signature = { hint_prefix = M.lsp.info }

M.border = {}

return M
